
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-07
owner: ucsb-cs156-f25
repo_name: team01-f25-07
pull_requests: [{"author":{"id":"U_kgDOCVINzA","is_bot":false,"login":"yuchaozheng05","name":""},"headRefName":"yc-put-for-ucsborganization-table","number":52,"title":"Yc put for ucsborganization table","url":"https://github.com/ucsb-cs156-f25/team01-f25-07/pull/52"},{"author":{"id":"U_kgDOCVINzA","is_bot":false,"login":"yuchaozheng05","name":""},"headRefName":"yc-ucsborganization-get-by-id","number":51,"title":"Yc - add get by id for ucsborganization","url":"https://github.com/ucsb-cs156-f25/team01-f25-07/pull/51"},{"author":{"id":"U_kgDOCVINzA","is_bot":false,"login":"yuchaozheng05","name":""},"headRefName":"yc-create-ucsborganization-controller","number":50,"title":"Yc -create ucsborganization controller, add GET/all and POST method","url":"https://github.com/ucsb-cs156-f25/team01-f25-07/pull/50"},{"author":{"id":"U_kgDOCVJ10Q","is_bot":false,"login":"ArmanSajjadian","name":""},"headRefName":"team01-dev-armansajjadian","number":48,"title":"ArmanSajjadian - create database for UCSBDiningCommonMenuItem","url":"https://github.com/ucsb-cs156-f25/team01-f25-07/pull/48"},{"author":{"id":"U_kgDOB2QVgw","is_bot":false,"login":"IanSheinis","name":"Ian Sheinis"},"headRefName":"feat/ArticlesController","number":47,"title":"Articles Apicontroller fully tested w/ mutations","url":"https://github.com/ucsb-cs156-f25/team01-f25-07/pull/47"}]
