
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-07
owner: ucsb-cs156-f25
repo_name: team01-f25-07
pull_requests: [{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"HelpRequestPut","number":77,"title":"Help request put","url":"https://github.com/ucsb-cs156-f25/team01-f25-07/pull/77"},{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"HelpRequestGet","number":76,"title":"Help request get","url":"https://github.com/ucsb-cs156-f25/team01-f25-07/pull/76"},{"author":{"id":"MDQ6VXNlcjUxOTAxMTQ3","is_bot":false,"login":"MatthewMandell","name":""},"headRefName":"HelpRequestController","number":75,"title":"controllah time","url":"https://github.com/ucsb-cs156-f25/team01-f25-07/pull/75"},{"author":{"id":"U_kgDOCVJ10Q","is_bot":false,"login":"ArmanSajjadian","name":""},"headRefName":"as-delete","number":74,"title":"as - delet for menu items, tests later","url":"https://github.com/ucsb-cs156-f25/team01-f25-07/pull/74"}]
